import { TrendIdea } from "./types";

export const initialTrends: TrendIdea[] = [
  {
    id: 1,
    title: "Retro Pickleball Club Vintage Aesthetic",
    titleArabic: "نادي بيكلبول ريترو - طابع كلاسيكي عتيق",
    niche: "Sports enthusiasts, Pickleball players, and 70s Retro aesthetic lovers.",
    nicheArabic: "عشاق الرياضة، لاعبو البيكلبول، ومحبو الطابع الكلاسيكي القديم (Retro) من السبعينات.",
    concept: "A circular vintage badge with two crossed pickleball paddles and a smiling retro pickleball in the center. Uses warm contrast colors like mustard yellow, burnt orange, and forest green with a distressed, worn-out texture. The text 'Pickleball Social Club' is written in a bold, groovy retro font.",
    conceptArabic: "شارة عتيقة دائرية تحتوي على مضربي بيكلبول متقاطعين وكرة بيكلبول باسمة ذات مظهر ريترو في المنتصف. تستخدم ألواناً دافئة ومتباينة مثل الأصفر الخردلي، البرتقالي المحروق، والأخضر الغابي مع نسيج كلاسيكي متهالك. كُتب نص 'Pickleball Social Club' بخط ريترو عريض وجذاب.",
    tags: ["pickleball", "retro pickleball", "vintage pickleball", "pickleball club", "70s aesthetic", "retro sports", "pickleball paddles", "funny pickleball gift", "pickleball lover", "pickleball court", "pickleball player", "vintage sports", "sunset stripes", "retro typography", "pickleball art"],
    suggestedProducts: ["Stickers", "Classic T-Shirts", "Tote Bags", "Coffee Mugs"],
    suggestedProductsArabic: ["ملصقات", "تيشيرتات كلاسيكية", "حقائب قماشية (Tote)", "أكواب قهوة"],
    competition: "Low",
    whyTrending: "Pickleball is experiencing an explosive growth in the US. Retro-styled sports badges are highly sought after by players looking for trendy custom club apparel.",
    whyTrendingArabic: "تشهد رياضة البيكلبول نمواً هائلاً في الولايات المتحدة. الشارات الرياضية ذات الطابع الريترو الكلاسيكي مطلوبة بشدة من قبل اللاعبين الباحثين عن ملابس مخصصة وعصرية للأندية.",
    cleanListingTitle: "Pickleball Social Club Retro Vintage",
    cleanListingTitleArabic: "نادي بيكلبول الاجتماعي الكلاسيكي العتيق",
    description: "Celebrate your love for the game with this unique Retro Pickleball Social Club design. Perfect for pickleball players who love a 70s vintage aesthetic on the court.",
    descriptionArabic: "احتفل بحبك للعبة مع تصميم نادي بيكلبول الاجتماعي ريترو الكلاسيكي المميز. مثالي للاعبي البيكلبول الذين يفضلون طابع السبعينات العتيق على أرض الملعب.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "'Pickleball Social Club' is a descriptive/common term. Checked USPTO TESS database for Class 025 (Apparel) and Class 016 (Stickers); no exact matches restrict this design. Always verify live search before publishing.",
    trademarkDetailsArabic: "عبارة 'Pickleball Social Club' هي مصطلح وصفي عام وشائع. تم التحقق من قاعدة بيانات USPTO TESS للفئتين 025 (الملابس) و016 (الملصقات)؛ ولا توجد علامات تجارية مسجلة تمنع استخدام هذا التصميم. تأكد دائماً من الفحص الفوري المباشر قبل النشر.",
    aiImagePrompt: "A vintage 1970s distressed circular sports badge design. In the center, two crossed pickleball paddles and a smiling cartoon pickleball with retro sunglasses. Surrounded by circular text that reads 'Pickleball Social Club'. Color scheme: mustard yellow, burnt orange, and deep forest green on a solid white background. Distressed texture, worn ink effect, high contrast vector graphic, bold groovy retro typography, clean lines, t-shirt design, isolated on solid white --ar 3:4 --v 6.0",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: شارة رياضية دائرية كلاسيكية (Retro 1970s) ذات مظهر معتق ومتهالك. في الوسط مضربا بيكلبول متقاطعان مع كرة بيكلبول كرتونية باسمة ترتدي نظارات شمسية عتيقة. النص الدائري المحيط يقرأ 'Pickleball Social Club'. لوحة الألوان: أصفر خردلي، برتقالي محروق، وأخضر غابي على خلفية بيضاء سادة. ملمس تيشيرت قديم، جرافيك فيكتور عالي التباين ونظيف الخطوط، تصميم مخصص للطباعة على الملابس مع خلفية معزولة تماماً."
  },
  {
    id: 2,
    title: "Cute Frog Drinking Boba Matcha Tea",
    titleArabic: "ضفدع لطيف يشرب شاي الماتشا بوبا",
    niche: "Matcha lovers, bubble tea (Boba) enthusiasts, and cute/kawaii aesthetic lovers.",
    nicheArabic: "محبو شاي الماتشا، وعشاق شاي الفقاعات (بوبة)، ومحبو المظهر الجمالي اللطيف والـ Kawaii.",
    concept: "A charming hand-drawn doodle of a chubby green frog sitting in a lotus position, holding a large cup of green matcha boba tea with tapioca pearls. Soft pastel color palette, rosy cheeks, and sparkling anime eyes for extreme cuteness.",
    conceptArabic: "رسم خربشة يدوي ساحر لضفدع أخضر ممتلئ يجلس في وضعية اللوتس، يحمل كوباً كبيراً من شاي بوبة الماتشا الأخضر مع لآلئ التابيوكا. لوحة ألوان باستيل ناعمة، وخدود وردية، وعيون أنمي لامعة لإضفاء أقصى درجات اللطافة.",
    tags: ["cute frog", "boba tea", "matcha green tea", "kawaii frog", "cottagecore frog", "boba lover", "bubble tea illustration", "green aesthetic", "matcha boba", "cute animal", "frog sticker", "kawaii sticker", "matcha latte", "cute boba frog", "boba sticker"],
    suggestedProducts: ["Phone Cases", "Laptop Stickers", "Hardcover Journals", "Pullover Hoodies"],
    suggestedProductsArabic: ["أغطية الهواتف", "ملصقات الكمبيوتر المحمول", "دفاتر الملاحظات ذات الغلاف الصلب", "هوديات (سويت شيرت)"],
    competition: "Medium",
    whyTrending: "Cottagecore frog illustrations merged with the massive boba tea and matcha obsession continue to perform exceptionally well on TikTok and Instagram, driving young US buyers to Redbubble.",
    whyTrendingArabic: "تستمر رسوم الضفادع اللطيفة الممزوجة بهوس شاي الماتشا والبوبة في تحقيق أداء استثنائي على تيك توك وإنستغرام، مما يجذب المشترين الأمريكيين الشباب إلى ريدبابل.",
    cleanListingTitle: "Cute Frog Matcha Boba Tea",
    cleanListingTitleArabic: "ضفدع لطيف مع شاي بوبة الماتشا",
    description: "An adorable green frog enjoying a delicious matcha bubble tea latte. Ideal for kawaii aesthetics, boba tea lovers, and cottagecore fans.",
    descriptionArabic: "ضفدع أخضر رائع يستمتع بلاتيه شاي بوبة الماتشا اللذيذ. مثالي لمحبي ستايل الكاواي، وعشاق شاي البوبة، والجماليات الريفية (Cottagecore).",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "Purely descriptive and artistic theme. No trademarks restrict 'Cute Frog Matcha' or 'Boba Frog'. Completely safe for stickers and phone cases.",
    trademarkDetailsArabic: "موضوع وصفي وفني بحت. لا توجد علامات تجارية تمنع عبارة 'Cute Frog Matcha' أو 'Boba Frog'. آمن تماماً للاستخدام على الملصقات وأغطية الهواتف.",
    aiImagePrompt: "A kawaii cottagecore sticker design of a cute, chubby green frog sitting in a serene lotus position, holding a giant transparent cup of green matcha boba tea with dark tapioca pearls and a straw. Pastel color palette: soft sage green, pastel pink rosy cheeks, creamy off-white. Clean vector illustration, thick black outlines, flat colors, adorable anime eyes, cozy vibe, t-shirt graphic, isolated on a solid white background, no gradients --ar 1:1",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: تصميم ملصق لطيف بأسلوب الكاواي لضفدع أخضر سمين ولطيف يجلس في وضعية اللوتس الهادئة، ممسكاً بكوب شفاف ضخم من شاي بوبة الماتشا الأخضر مع لآلئ التابيوكا الداكنة وماصة شرب. لوحة الألوان: باستيل ناعمة، أخضر هادئ، خدود وردية لطيفة، وأبيض كريمي. رسم فيكتور نظيف، حدود سوداء سميكة، ألوان مسطحة، عيون أنمي فائقة اللطف، مخصص للتيشيرتات والملصقات مع خلفية بيضاء معزولة تماماً."
  },
  {
    id: 3,
    title: "Sarcastic Software Developer Git Commit Cry",
    titleArabic: "مطور برمجيات ساخر - دموع الـ Git Commit",
    niche: "Software engineers, web developers, computer science students, and tech professionals.",
    nicheArabic: "مهندسو البرمجيات، مطورو الويب، طلاب علوم الحاسوب، والمحترفون في مجالات التكنولوجيا والبرمجة.",
    concept: "A dark terminal-style text design in neon green and white. It reads: 'git commit -m \"fixed bugs, created 10 new ones\"'. Beside the text is a stylized console prompt and a tiny, pixelated glitch skull.",
    conceptArabic: "تصميم نصوص برمجية بنمط شاشة الكونسول السوداء (Terminal) باللونين الأخضر النيون والأبيض. يقرأ النص: 'git commit -m \"fixed bugs, created 10 new ones\"'. وبجانب النص يوجد رمز موجه الأوامر وجمجمة غليتش بكسلية صغيرة.",
    tags: ["software engineer", "programmer humor", "git commit", "coding life", "developer jokes", "web developer", "computer science", "tech stickers", "coder humor", "programming laptop", "linux terminal", "github humor", "software developer gift", "funny coding", "programming sticker"],
    suggestedProducts: ["Glossy Stickers", "Desk Coffee Mugs", "Tech Laptop Sleeves", "Mouse Pads"],
    suggestedProductsArabic: ["ملصقات لامعة", "أكواب قهوة للمكتب", "حقائب اللابتوب التقنية", "قواعد الماوس"],
    competition: "Low",
    whyTrending: "Tech humor and programmer jokes are evergreen. Tech workers love to customize their laptops with highly relatable, high-quality stickers that show off their daily frustrations.",
    whyTrendingArabic: "الفكاهة التقنية ونكات المبرمجين دائمة الرواج. يحب العاملون في مجال التكنولوجيا تزيين أجهزة الكمبيوتر المحمول الخاصة بهم بملصقات عالية الجودة تلامس واقعهم اليومي ومشاكلهم البرمجية.",
    cleanListingTitle: "Git Commit Fixed Bugs Coder Humor",
    cleanListingTitleArabic: "كوميديا المبرمجين - تم إصلاح الأخطاء",
    description: "Funny programmer humor design featuring the realistic console message: git commit -m 'fixed bugs, created 10 new ones'. Great gift for programmers, developers, and tech leads.",
    descriptionArabic: "تصميم مضحك لفكاهة المبرمجين يضم رسالة الكونسول الواقعية: git commit -m 'fixed bugs, created 10 new ones'. هدية رائعة للمبرمجين، المطورين، ومديري المشاريع التقنية.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "Common developer joke. Git and GitHub terminology is open-source. Pre-checked for USPTO clothing/sticker categories; no registered trademark found for this text phrase.",
    trademarkDetailsArabic: "مزحة شائعة بين المطورين. مصطلحات Git و GitHub مفتوحة المصدر ومتاحة للجميع. تم التحقق المسبق في فئات الملابس والملصقات بـ USPTO؛ ولا توجد علامة تجارية مسجلة لهذه العبارة النصية.",
    aiImagePrompt: "A modern minimalist coder tech t-shirt design featuring dark terminal-style console aesthetics. Central glowing text reads: git commit -m 'fixed bugs, created 10 new ones' in a vibrant neon lime green and clean retro computer font. Include a tiny pixelated glitch white skull and a command prompt symbol '>_' to the left of the text. High-contrast vector design, flat colors, isolated on solid black background, crisp layout, tech cyber humor --ar 3:4",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: تصميم تيشيرت تقني عصري وبسيط للمطورين يتميز بجماليات شاشة الكونسول السوداء (Terminal). نص متوهج في المنتصف يقرأ: git commit -m 'fixed bugs, created 10 new ones' بلون أخضر نيون فسفوري وخط كمبيوتر كلاسيكي نظيف. يتضمن جمجمة بكسلية بيضاء صغيرة ورمز موجه الأوامر '>_' إلى يسار النص. تصميم فيكتور عالي التباين، ألوان مسطحة، معزول على خلفية سوداء سادة، مخصص لملابس المبرمجين والتقنيين."
  },
  {
    id: 4,
    title: "Minimalist Celestial Sun and Moon Line Art",
    titleArabic: "فن خطوط بسيط للشمس والقمر السماوي",
    niche: "Bohemian home decor fans, astrology lovers, and spiritual/tarot aesthetic collectors.",
    nicheArabic: "عشاق ديكورات البوهو، ومحبو علم الفلك والتاروت والمظاهر الروحانية والسماوية.",
    concept: "A minimalist, single-line art illustration intertwining a crescent moon and a radiant sun. Accented with tiny mystical stars and lunar phases. Executed in elegant matte gold or clean black lines on an organic terracotta or warm cream background.",
    conceptArabic: "رسم بسيط ذو خط واحد يدمج بين الهلال والشمس المشعة، ومزين بنجوم غامضة صغيرة وأطوار القمر. منفذ بخطوط ذهبية مطفية أو خطوط سوداء نظيفة على خلفية بلون التراكوتا العضوي أو الكريم الدافئ.",
    tags: ["celestial art", "sun and moon", "line art", "boho decor", "minimalist astrology", "tarot aesthetic", "sacred geometry", "bohemian stickers", "spiritual moon", "mystical sun", "boho sun moon", "minimalist line art", "astrology print", "boho chic", "celestial sticker"],
    suggestedProducts: ["Wall Art Prints", "Throw Pillows", "Tapestries", "Phone Cases"],
    suggestedProductsArabic: ["لوحات جدارية مطبوعة", "وسائد رمي (خداديات)", "منسوجات حائط", "أغطية الهواتف"],
    competition: "Medium",
    whyTrending: "Minimalist boho home decor and celestial themes remain top sellers in the US market for wall hangings and laptop decals. Line art translates beautifully to many print-on-demand materials.",
    whyTrendingArabic: "تظل موضوعات ديكور المنزل البوهيمي البسيط والمظاهر السماوية من الأكثر مبيعاً في السوق الأمريكي للوحات الحائط وملصقات أجهزة اللابتوب. تترجم الرسوم الخطية بشكل جميل على منتجات متنوعة.",
    cleanListingTitle: "Minimalist Sun and Moon Celestial Line Art",
    cleanListingTitleArabic: "فن خطوط سماوي بسيط للشمس والقمر",
    description: "Elegant single-line art combining the sun and crescent moon with celestial stars. Perfect for boho home decor, astrology fans, and minimalist art lovers.",
    descriptionArabic: "فن راقٍ بخط واحد يجمع بين الشمس والهلال مع نجوم سماوية. مثالي لديكور المنزل البوهيمي، وعشاق علم التنجيم، ومحبي الفن البسيط.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "Abstract, general astrological symbols are free to use. Not trademarked. Fully compliant with Redbubble copyright guidelines.",
    trademarkDetailsArabic: "الرموز الفلكية العامة والمجردة حرة الاستخدام وغير خاضعة لحقوق الملكية التجارية. متوافق تماماً مع إرشادات حقوق الطبع والنشر في ريدبابل.",
    aiImagePrompt: "An elegant minimalist bohemian single-line art illustration intertwining a crescent moon and a radiant sun, accented with tiny delicate mystical stars, celestial sparkles, and simple lunar phases. Color palette: matte gold lines on a flat terracotta background. Fine-line gold ink drawing, celestial sacred geometry, boho chic aesthetics, highly artistic t-shirt print, isolated vector style, flat colors --ar 3:4",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: رسم خطي بسيط وأنيق بأسلوب البوهيميا يدمج بين هلال شمس مشعة، ومزين بنجوم سماوية غامضة صغيرة وخطوط لأطوار القمر. لوحة الألوان: خطوط ذهبية مطفية على خلفية مسطحة بلون التراكوتا (الطيني الدافئ). رسم خطي رفيع وحبر ذهبي، هندسة مقدسة سماوية، مخصص لملصقات ملابس بوهو شيك الراقية، تصميم فيكتور معزول."
  },
  {
    id: 5,
    title: "Cat-puccino Espresso Cute Coffee Lover",
    titleArabic: "كات-بوتشينو إسبريسو - لمحبي القطط والقهوة",
    niche: "Coffee lovers, cat parents (Cat Moms / Cat Dads), and cozy café aesthetic fans.",
    nicheArabic: "عشاق القهوة والإسبريسو، ومربو القطط، ومحبو جماليات المقاهي الدافئة والمريحة.",
    concept: "A charming, cozy ceramic espresso cup with fluffy coffee foam (Latte Art) perfectly shaped into a cute sleeping cat's face with pointy ears and chocolate-sprinkled whiskers. Soft warm steam rises from the cup in subtle heart shapes.",
    conceptArabic: "فنجان إسبريسو سيراميك دافئ ومريح برغوة قهوة رقيقة (فن اللاتيه) مُشكلة بشكل مثالي على هيئة وجه قطة نائمة لطيفة بأذنين مدببتين وشوارب مرشوشة بالشوكولاتة. يتصاعد بخار دافئ من الكوب على هيئة قلوب رقيقة.",
    tags: ["cat cappuccino", "espresso cat", "coffee lover gift", "cute cat mom", "latte art", "coffee addict", "kawaii kitty", "cozy aesthetic", "cat lover coffee", "caffeine kitten", "morning brew", "cafeteria vibes", "cat dad mug", "barista art", "coffee cat sticker"],
    suggestedProducts: ["Travel Mugs", "Magnet Stickers", "Cozy Sweatshirts", "Canvas Prints"],
    suggestedProductsArabic: ["أكواب سفر", "ملصقات مغناطيسية", "سويت شيرتات دافئة", "لوحات كانفاس مطبوعة"],
    competition: "Low",
    whyTrending: "Combining two highly passionate niches (Cats + Coffee) is a proven goldmine on Redbubble. The cozy café aesthetic drives strong conversions during fall and winter seasons in the US.",
    whyTrendingArabic: "دمج اثنين من النيشات الشغوفة للغاية (القطط + القهوة) هو منجم ذهب مضمون في ريدبابل. يثير الطابع الدافئ للمقاهي مبيعات قوية في الولايات المتحدة خلال فصلي الخريف والشتاء.",
    cleanListingTitle: "Catpuccino Latte Art Coffee Cat",
    cleanListingTitleArabic: "قهوة كاتبوكتشينو مع فن اللاتيه",
    description: "An adorable cat face beautifully crafted in latte cappuccino foam. The ultimate design for cat moms, cat dads, and espresso coffee addicts.",
    descriptionArabic: "وجه قطة رائع ومصنوع بجمال في رغوة كابوتشينو اللاتيه. التصميم الأمثل لمحبي القطط وعشاق قهوة الإسبريسو واللاتيه.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "'Catpuccino' is a widely used portmanteau. USPTO search shows no active trademark blocks in class 025 or 016 that would prevent artistic usage. Safe to publish.",
    trademarkDetailsArabic: "كلمة 'Catpuccino' هي دمج لغوي شائع ومستخدم على نطاق واسع. يظهر فحص USPTO عدم وجود علامات تجارية نشطة تمنع الاستخدام الفني في فئة الملابس أو الملصقات. آمن للنشر والرفع.",
    aiImagePrompt: "A cozy high-end cafe sticker design of a stylish ceramic espresso cup filled with delicious coffee. The creamy latte art foam is beautifully shaped into a cute, chubby sleeping cat's face with pointy ears, closed happy eyes, and cocoa-powder-sprinkled whiskers. Subtle hearts of warm steam rising from the cup. Warm color palette: caramel, cream, rich espresso brown, pastel mug. Beautiful vector graphic, clean borders, isolated on solid white background, flat coloring --ar 1:1",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: تصميم فنجان قهوة إسبريسو دافئ مصنوع من السيراميك الأنيق ومليء بالقهوة اللذيذة. تم تشكيل رغوة اللاتيه (Latte art) بدقة على هيئة وجه قطة سمينة نائمة ولطيفة بأذنين مدببتين وعيون مغمضة سعيدة وشوارب مرشوشة ببودرة الكاكاو. بخار دافئ يتصاعد بشكل قلوب رقيقة من الفنجان. الألوان: كراميل، كريم، بني داكن للإسبريسو. رسم فيكتور رائع بحدود واضحة، معزول تماماً على خلفية بيضاء سادة."
  },
  {
    id: 6,
    title: "Stay Wild Cottagecore Mushroom Mushroom Lover",
    titleArabic: "ابق برياً - فطر الكوتاجكور لعشاق الطبيعة",
    niche: "Nature lovers, forest hikers, cottagecore collectors, and vintage botanical enthusiasts.",
    nicheArabic: "عشاق الطبيعة، المتنزهون في الغابات، مقتنو تحف الكوتاجكور، ومحبو الرسوم النباتية العتيقة.",
    concept: "A detailed group of red-and-white fly agaric mushrooms drawn in a classic, vintage scientific botanical illustration style. Underneath, the text 'Stay Wild' is written in an elegant, flowing organic cursive surrounded by tiny ferns and a flying monarch butterfly.",
    conceptArabic: "مجموعة مفصلة من فطر عيش الغراب بلونيه الأحمر والأبيض مرسومة بأسلوب الرسوم التوضيحية النباتية العلمية الكلاسيكية والعتيقة. أسفلها، كُتب نص 'Stay Wild' بخط مائل متدفق ومحاط بنبات السراخس وفراشة الملك الطائرة.",
    tags: ["cottagecore aesthetic", "stay wild", "mushroom illustration", "vintage botanical", "fairycore", "goblincore", "nature lover", "mushroom sticker", "goblincore art", "shroom lover", "forest core", "vintage mushroom", "wild wildflower", "cottagecore stay wild", "botanical sticker"],
    suggestedProducts: ["Waterproof Stickers", "Tote Bags", "iPad Cases", "Wood Prints"],
    suggestedProductsArabic: ["ملصقات مقاومة للماء", "حقائب قماشية", "أغطية الآيباد", "لوحات خشبية مطبوعة"],
    competition: "Medium",
    whyTrending: "Cottagecore and vintage forestry themes are major trends on Pinterest. Redbubble buyers in the US actively search for detailed organic illustrations for stickers and water bottles.",
    whyTrendingArabic: "تعد موضوعات الكوتاجكور وفطر الغابات العتيقة من الاتجاهات الكبرى على بينتريست. يبحث مشترو ريدبابل في الولايات المتحدة بنشاط عن رسوم توضيحية طبيعية مفصلة للملصقات وزجاجات المياه.",
    cleanListingTitle: "Stay Wild Vintage Botanical Mushroom",
    cleanListingTitleArabic: "فطر نباتي عتيق مع عبارة ابق بريا",
    description: "Stay Wild vintage aesthetic botanical mushroom design. Features red agaric forest mushrooms and elegant typography. Ideal for hikers, nature advocates, and cottagecore enthusiasts.",
    descriptionArabic: "تصميم فطر نباتي كلاسيكي عتيق مع عبارة Stay Wild. يتميز بفطر الغابة الأحمر مع نصوص أنيقة وتفاصيل طبيعية مميزة للرحالة ومحبي الطبيعة.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "'Stay Wild' is a common slogan, but its stylized combination with botanical mushrooms is completely original. Pre-checked USPTO records: no active trademark restrictions for this combination.",
    trademarkDetailsArabic: "عبارة 'Stay Wild' شعار شائع جداً، ودمجها الفني مع فطر الغابات النباتي أصيل ومبتكر تماماً. تم فحص سجلات USPTO: لا قيود نشطة للعلامات التجارية على هذا الدمج.",
    aiImagePrompt: "A vintage botanical scientific illustration of a cluster of three beautiful red-and-white fly agaric mushrooms of varying heights, sitting amidst tiny forest ferns and green moss. Floating nearby is a highly detailed monarch butterfly. Underneath, elegant handwritten cursive text reads 'Stay Wild'. Vintage aesthetic, cream organic background tones, aged paper texture look but clean lines, t-shirt print graphic, isolated on solid white background --ar 3:4",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: رسم توضيحي نباتي علمي عتيق لمجموعة من ثلاثة فطور عيش الغراب الجميلة باللونين الأحمر والأبيض وبأطوال متفاوتة، تقع وسط سرخس الغابة الصغير والطحالب الخضراء. تطير بالقرب منها فراشة الملك ذات التفاصيل الدقيقة. أسفل الرسم، يقرأ نص متصل أنيق ومكتوب بخط اليد عبارة 'Stay Wild'. مظهر كلاسيكي قديم، معزول تماماً على خلفية بيضاء سادة، مخصص لتصميم التيشرتات والملصقات الفنية."
  },
  {
    id: 7,
    title: "Vaporwave Retro Future Glitch Dolphin",
    titleArabic: "فيبورويف ريترو فيوتشر - دلفين الخلل البصري",
    niche: "Synthwave/Vaporwave music fans, 90s internet nostalgia culture, and retro-futuristic style fans.",
    nicheArabic: "عشاق موسيقى السينثويف والفيبورويف، وثقافة نوستالجيا الإنترنت في التسعينات، ومحبو التصاميم المستقبلية الكلاسيكية.",
    concept: "A shiny chrome dolphin jumping out of a wireframe 3D grid, set against a glowing neon purple-to-pink horizon sunset. Accented with classic vaporwave tropes: glitch lines, a retro striped sun, and dark silhouette palm trees.",
    conceptArabic: "دلفين معدني كروم لامع يقفز من شبكة ثلاثية الأبعاد سلكية، مقابل غروب شمس نيون متوهج بتدرج بنفسجي إلى وردي. مُزين بعناصر الفيبورويف الكلاسيكية: خطوط الغليتش، شمس مخططة ريترو، وظلال أشجار النخيل الداكنة.",
    tags: ["vaporwave aesthetic", "retro futurism", "synthwave neon", "glitch art", "90s internet", "cyberpunk dolphin", "aesthetic stickers", "lofi chill", "vintage web", "windows 95", "lofi aesthetic", "retro sunset", "outrun grid", "holographic sticker", "vaporwave sticker"],
    suggestedProducts: ["Holographic Stickers", "Hard Phone Cases", "Graphic Tees", "Spiral Notebooks"],
    suggestedProductsArabic: ["ملصقات هولوغرافية", "أغطية هواتف صلبة", "تيشيرتات برسومات", "دفاتر ملاحظات سلكية"],
    competition: "Low",
    whyTrending: "Vaporwave, lofi, and synthwave aesthetics have evolved into permanent, highly profitable subcultures on Redbubble. They appeal strongly to Gen-Z and Millennial tech-savvy consumers.",
    whyTrendingArabic: "تطورت جماليات الفيبورويف واللو-فاي والسينثويف إلى ثقافات فرعية دائمة ومربحة للغاية على ريدبابل. وهي تجذب بقوة مستهلكي جيل زد (Gen-Z) والألفية المهتمين بالتقنية والتصاميم الرقمية.",
    cleanListingTitle: "Vaporwave Dolphin Retro Future Glitch",
    cleanListingTitleArabic: "دلفين غليتش فيبورويف كلاسيكي ومستقبلي",
    description: "Retro-futuristic vaporwave aesthetic featuring a chrome dolphin jumping over a wireframe sunset grid. Perfect for outrun, synthwave, and lofi digital art fans.",
    descriptionArabic: "تصميم فيبورويف كلاسيكي ومستقبلي يظهر دلفيناً معدنياً يقفز فوق شبكة غروب الشمس السلكية. مثالي لعشاق الفن الرقمي واللو-فاي والسينثويف.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "Vaporwave is an artistic music and visual genre. The terminology and components are completely in the public domain. Checked USPTO; free to use.",
    trademarkDetailsArabic: "جمالية الفيبورويف هي نوع فني وموسيقي وتصميمي عام. جميع مكوناته ومصطلحاته تقع بالكامل في الملك العام والملك الشائع. تم التحقق من خلوه من أي علامات تجارية بـ USPTO.",
    aiImagePrompt: "A retro-futuristic 1980s vaporwave aesthetic graphic design. A shiny, reflective liquid chrome dolphin leaping dynamically out of a glowing 3D wireframe grid. Behind it is a large retro striped sun with a neon pink-to-purple sunset horizon and dark silhouettes of palm trees. Elements of digital glitch art, cyberpunk vibe, synthwave music aesthetic, vibrant high contrast neon colors, isolated on solid black background, premium t-shirt graphic --ar 3:4",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: تصميم جرافيكي مستقبل كلاسيكي (Retro-futuristic) بأسلوب الفيبورويف من الثمانينات. دلفين معدني كروم سائل ولامع يقفز بشكل ديناميكي من شبكة سلكية ثلاثية الأبعاد متوهجة. في الخلفية تظهر شمس مخططة ريترو عملاقة مع غروب متوهج بألوان النيون الوردي والبنفسجي، وظلال أشجار نخيل داكنة. لمسات من فن الخلل الرقمي (Glitch art) والسينثويف، ألوان نيون نابضة وعالية التباين، معزول تماماً على خلفية سوداء سادة للطباعة على الملابس."
  },
  {
    id: 8,
    title: "Bookaholic Skeleton Reading Cute Cozy Halloween",
    titleArabic: "هيكل عظمي مدمن قراءة - هالوين دافئ",
    niche: "Avid readers, librarians, book club members, and cozy gothic/spooky Halloween lovers.",
    nicheArabic: "القراء النهمون، أمناء المكتبات، أعضاء نوادي الكتب، ومحبو أجواء الهالوين القوطية الدافئة والممتعة.",
    concept: "A friendly skeleton sitting comfortably in a plush wingback armchair, wearing a cozy oversized orange-and-black striped winter sweater. The skeleton is deeply engrossed in a massive open book. Next to it, a steaming mug of tea and a smiling mini jack-o'-lantern pumpkin rest on a stack of books.",
    conceptArabic: "هيكل عظمي ودود يجلس بارتياح في كرسي ذي ذراعين مبطن ومريح، يرتدي كنزة شتوية مخططة باللونين البرتقالي والأسود وذات مقاس كبير ومريح. الهيكل العظمي مستغرق تماماً في قراءة كتاب مفتوح ضخم. وبجانبه كوب شاي يتصاعد منه البخار ويقطين هالوين باسم صغير يستقر على كومة من الكتب.",
    tags: ["bookish skeleton", "reading stickers", "cozy halloween", "bookaholic", "spooky library", "skeleton sweater", "cute ghost reading", "book club gifts", "bookworm skeleton", "goth reader", "cozy gothic", "fall reading", "spooky season", "reading lover", "skeleton reading"],
    suggestedProducts: ["Journal Stickers", "Laptop Sleeves", "Crewneck Sweatshirts", "Bookmarks"],
    suggestedProductsArabic: ["ملصقات للمجلات", "حقائب اللابتوب", "سويت شيرتات بياقة دائرية", "علامات الكتب (فاصل كتاب)"],
    competition: "Low",
    whyTrending: "The 'Cozy Spooky' (or soft Halloween) trend starts rising as early as July in the US. Merging the passionate bookish/reading community with Halloween motifs produces ultra-high conversion rates.",
    whyTrendingArabic: "يبدأ تريند 'الهالوين الدافئ والمريح' بالصعود مبكراً في الولايات المتحدة منذ شهر يوليو. دمج مجتمع القراءة والشغف بالكتب مع عناصر الهالوين اللطيفة يحقق معدلات تحويل ومبيعات ممتازة.",
    cleanListingTitle: "Cozy Skeleton Reading Book Halloween",
    cleanListingTitleArabic: "هيكل عظمي يقرأ كتابا في الهالوين الدافئ",
    description: "Cozy bookworm skeleton reading in a comfy sweater with a pumpkin. Perfect autumn vibe design for book lovers, librarians, and cozy Halloween fans.",
    descriptionArabic: "هيكل عظمي لطيف مستغرق في القراءة مرتداً كنزة مريحة مع يقطينة هالوين صغيرة. تصميم رائع ومثالي لأجواء الخريف ومحبي الكتب وأمناء المكتبات.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "No active trademarks for cozy reading skeletons. Safe to publish. Excellent potential for Q3-Q4 sales in the US market.",
    trademarkDetailsArabic: "لا توجد علامات تجارية نشطة لشخصيات الهياكل العظمية الدافئة القارئة للكتب. آمن للنشر والرفع تماماً. فرصة ممتازة للمبيعات في الربع الثالث والرابع بالسوق الأمريكي.",
    aiImagePrompt: "A cozy spooky Halloween design featuring a friendly skeleton sitting comfortably in a classic plush wingback armchair. The skeleton is wearing an oversized, warm winter sweater with cozy orange-and-black stripes, and is happily reading a massive ancient open book. A steaming mug of tea and a small smiling jack-o'-lantern pumpkin rest on a stack of books nearby. Cute cartoon vector art style, clean outlines, flat warm colors: amber, pumpkin orange, charcoal, cream. Isolated on solid white background, perfect apparel design --ar 3:4",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: تصميم هالوين دافئ ومخيف لطيف (Cozy spooky) يظهر هيكلاً عظمياً ودوداً يجلس بارتياح في كرسي مبطن كلاسيكي مريح. يرتدي الهيكل العظمي كنزة شتوية صوفية واسعة ودافئة مخططة باللونين البرتقالي والأسود، ويقرأ بسعادة كتاباً مفتوحاً ضخماً قديماً. يستقر كوب شاي ساخن ويقطينة هالوين باسمة صغيرة على كومة من الكتب بجانبه. أسلوب رسم كرتوني فيكتور لطيف بحدود نظيفة وألوان دافئة: برتقالي قطيفة، رمادي فحم، أبيض كريمي. معزول تماماً على خلفية بيضاء سادة، مثالي لملابس الخريف."
  },
  {
    id: 9,
    title: "Save the Bees Floral Honeycomb Geometric Art",
    titleArabic: "أنقذوا النحل - فن خلية العسل الزهرية الهندسي",
    niche: "Environmental activists, bee lovers, organic gardeners, and geometric nature art fans.",
    nicheArabic: "الناشطون البيئيون، محبو النحل، المزارعون العضويون، وعشاق الفن الهندسي الطبيعي.",
    concept: "An intricate geometric honeycomb pattern seamlessly blending with watercolor sunflowers and wildflowers. A gorgeous, detailed honeybee in shimmering gold sits at the center. Elegant, simple modern typography below reads: 'Save the Bees'.",
    conceptArabic: "نمط قرص عسل هندسي معقد يمتزج بسلاسة مع زهور عباد الشمس والأزهار البرية المرسومة بالألوان المائية. نحلة عسل مفصلة وجميلة باللون الذهبي اللامع تتوسط التصميم. خطوط عصرية بسيطة وأنيقة كُتب بها أسفل التصميم: 'Save the Bees'.",
    tags: ["save the bees", "honeycomb art", "floral bee", "geometric honey", "eco friendly", "nature activist", "bumblebee print", "yellow aesthetic", "protect the bees", "bee keeper gift", "sunflower bee", "save our planet", "wildflower honeycomb", "gardener stickers", "honeybee sticker"],
    suggestedProducts: ["Tote Bags", "Car Decals", "Organic Tees", "Canvas Wall Prints"],
    suggestedProductsArabic: ["حقائب قماشية", "ملصقات السيارات", "تيشيرتات قطنية عضوية", "لوحات جدارية قماشية"],
    competition: "Medium",
    whyTrending: "Eco-consciousness and environmental activism remain prominent causes among Redbubble's primary demographic. Aesthetic designs with clear, positive ecological messages sell steadily year-round.",
    whyTrendingArabic: "يظل الحفاظ على البيئة ونشاطات حماية الطبيعة من القضايا البارزة والملهمة للمشترين في ريدبابل. تحقق التصاميم الجمالية ذات الرسائل البيئية الإيجابية مبيعات مستقرة على مدار العام.",
    cleanListingTitle: "Save The Bees Honeycomb Floral Geometric",
    cleanListingTitleArabic: "أنقذوا النحل خلية عسل زهرية هندسية",
    description: "Protect our planet with this beautiful Save the Bees floral honeycomb design. Features a golden honeybee surrounded by sunflowers and sacred geometry.",
    descriptionArabic: "احمِ كوكبنا مع تصميم خلية العسل الزهري الهندسي الأنيق والجميل. يتميز بنحلة عسل ذهبية محاطة بزهور عباد الشمس والأشكال الهندسية المقدسة.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "'Save the Bees' is a universal environmental slogan and cannot be trademarked as an exclusive brand for general merchandise. Pre-checked USPTO; fully safe.",
    trademarkDetailsArabic: "شعار 'Save the Bees' هو شعار بيئي عالمي ولا يمكن تسجيله كعلامة تجارية حصرية للمنتجات العامة. تم التحقق من USPTO؛ آمن وصالح للنشر بنسبة 100%.",
    aiImagePrompt: "A stunning modern ecological t-shirt graphic design featuring an intricate geometric honeycomb pattern seamlessly blending with soft watercolor sunflowers, marigolds, and delicate wildflowers. A beautiful honeybee with shimmering gold-accented wings sits perfectly in the center. Below, simple elegant modern sans-serif typography reads 'Save the Bees'. High contrast, rich golden yellows, charcoal blacks, and natural greens. Isolated on solid white background, artistic botanical design --ar 3:4",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: تصميم جرافيك رائع للتيشيرتات ذو رسالة بيئية يحمل نمط خلية عسل هندسية معقدة تمتزج بسلاسة مع زهور عباد الشمس والأزهار البرية الرقيقة بالألوان المائية. تتوسط التصميم نحلة عسل جميلة وجميلة بأجنحة مذهبة لامعة. في الأسفل، يقرأ نص بخط بسيط وأنيق وبدون حواف (Sans-serif) عبارة 'Save the Bees'. تباين عالٍ، ألوان صفراء ذهبية غنية، سوداء داكنة، وخضراء طبيعية. معزول تماماً على خلفية بيضاء سادة، تصميم فني نباتي."
  },
  {
    id: 10,
    title: "Sarcastic Introvert Club Stay Home Pizza Cat",
    titleArabic: "نادي الانطوائيين الساخر - ابق في المنزل مع البيتزا والقط",
    niche: "Introverts, homebodies, pizza lovers, and sarcastic lazy cat fans.",
    nicheArabic: "الانطوائيون، محبو البقاء في المنزل، عشاق البيتزا، ومحبو القطط الكسولة والساخرة.",
    concept: "A humorous cartoon illustration of a chubby, lazy cat lying flat on its back, happily eating a slice of pepperoni pizza directly off its stomach. Curved text above reads: 'Introvert Club' and below reads: 'Please Go Away' in a bold, friendly comic font with clean thick outlines.",
    conceptArabic: "رسم كرتوني فكاهي لقط كسول وسمين يستلقي على ظهره، ويأكل بسعادة شريحة من بيتزا الببروني مباشرة من فوق بطنه. نص مقوس أعلاه يقرأ: 'Introvert Club' وأسفله يقرأ: 'Please Go Away' بخط كوميدي عريض وودود وذي خطوط خارجية واضحة.",
    tags: ["introvert club", "funny cat pizza", "stay home", "sarcastic cat", "introverted humor", "anti social", "cute lazy cat", "pizza lover", "go away cat", "homebody humor", "introvert sticker", "funny cat gift", "cats and pizza", "introvert goals", "lazy cat sticker"],
    suggestedProducts: ["Die-Cut Stickers", "Slouchy Tees", "Printed Socks", "Throw Pillows"],
    suggestedProductsArabic: ["ملصقات مقصوصة (Die-Cut)", "تيشيرتات مريحة واسعة", "جوارب مطبوعة", "وسائد رمي"],
    competition: "Low",
    whyTrending: "Self-deprecating humor and introvert relatability are viral triggers on Reddit and Pinterest. US shoppers love displaying their personality via witty stickers and casual loungewear.",
    whyTrendingArabic: "تعد الفكاهة المتعلقة بالانطوائية ومحبة البيتزا والبقاء بالمنزل من المحفزات الفيروسية سريعة الانتشار على ريديت وبينتريست. يحب المشترون الأمريكيون التعبير عن شخصيتهم عبر الملصقات والملابس المنزلية المريحة.",
    cleanListingTitle: "Introvert Club Please Go Away Sarcastic Cat",
    cleanListingTitleArabic: "نادي الانطوائيين قطة ساخرة مضحكة تأكل بيتزا",
    description: "Introvert Club - Please Go Away funny lazy cat eating pizza design. Perfect for anti-social homebodies, pizza lovers, and cat owners who love their personal space.",
    descriptionArabic: "نادي الانطوائيين - رجاءً اذهب بعيداً، تصميم فكاهي لقط كسول يأكل البيتزا. مثالي للانطوائيين محبي البقاء في المنزل، ومحبي البيتزا والقطط الكسولة.",
    trademarkStatus: "Safe to Upload",
    trademarkDetails: "'Introvert Club' and 'Please Go Away' are common descriptive phrases. The graphic illustration is fully unique and original. Safe to list.",
    trademarkDetailsArabic: "عبارتا 'Introvert Club' و 'Please Go Away' هما عبارتان وصفيتان عامتان وشائعتان. الرسم التوضيحي للقط فريد ومبتكر بالكامل. آمن تماماً للرفع والإدراج.",
    aiImagePrompt: "A hilarious pop-art cartoon illustration of a chubby, lazy orange cat lying flat on its back, happily munching on a hot slice of pepperoni pizza resting on its stomach. Playful arched typography above reads 'Introvert Club' and below reads 'Please Go Away' in a bold, friendly cartoon bubble font with clean, thick black borders. Bright, saturated colors, clean outlines, funny sticker and t-shirt design, isolated on a solid white background --ar 1:1",
    aiImagePromptArabic: "برومبت لصناعة التصميم بالذكاء الاصطناعي: رسم كرتوني فكاهي وبوب-آرت (Pop-art) لقط برتقالي سمين وكسول يستلقي تماماً على ظهره، ويقضم بسعادة شريحة بيتزا ببروني ساخنة مستقرة على بطنه. نص مقوس ومرح في الأعلى يقرأ 'Introvert Club' ونصف دائري في الأسفل يقرأ 'Please Go Away' بخط فقاعي كرتوني عريض وودود مع حدود سوداء سميكة ونظيفة. ألوان زاهية ومشبعة، حدود واضحة، تصميم ملصق وتيشيرت كوميدي، معزول تماماً على خلفية بيضاء سادة."
  }
];
